name: VirTect
channels:
  - bioconda
  - conda-forge
dependencies:
  - python=3.6
  - pip
  - prodigal
  - biopython
  - jupyterlab
  - pip:
    - numpy
    - pandas
    - matplotlib
    - wget
    - scipy
